version: '3.1'

services:
  elasticsearch:
    image: elasticsearch
    restart: always
    ports: 
      - 9200:9200
      - 9300:9300
  db:
    image: postgres:9.5
    restart: always
    container_name: db
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports: 
     - 5432:5432
  rails: 
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: rb
    restart: always
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      - SECRET_KEY_BASE=3eaa9178c5728347e93d431a61061bac6b4d62ffa62840d269168b1250e26364180d65dc91555a47d472f32542e4d7bbc9f4452cb2efbf45c5ac7038194cc02c
      - RECRUITINGBOARD_DATABASE_PASSWORD=mysecretpassword
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - TERM=xterm 
    volumes:
      - ./rb:/home/rb
    ports:
      - "3000:3000" 
    links:
      - elasticsearch
      - db